#!/usr/bin/env python
# $Id: SkeletonPage.py,v 1.3 2001/06/18 22:25:09 tavis_rudd Exp $
"""A skeleton page template for use with the Cheetah package

Meta-Data
==========
Author: Tavis Rudd <tavis@calrudd.com>,
Version: $Revision: 1.3 $
Start Date: 2001/04/05
Last Revision Date: $Date: 2001/06/18 22:25:09 $
"""
__author__ = "Tavis Rudd <tavis@calrudd.com>"
__version__ = "$Revision: 1.3 $"[11:-2]

##################################################
## DEPENDENCIES ##

import types, os, sys


from Cheetah.Servlet import TemplateServlet
import Cheetah.Macros.HTML as HTMLMacros
from Cheetah.Macros.HTML import spacer, currentYr, formHTMLTag, formatMetaTags

##################################################
## GLOBALS AND CONSTANTS ##

True = (1==1)
False = (0==1)

##################################################
## TEMPLATE ELEMENTS ##

template = """$*docType
<HTML>
####################
#block headerComment
<!-- This document was autogenerated by Cheetah. Don't edit it directly!

Copyright #currentYr() - $*siteCopyrightName - All Rights Reserved.
Feel free to copy any javascript or html you like on this site,
provided you remove all links and/or references to $*siteDomainName
However, please do not copy any content or images without permission.

$*siteCredits

-->

#end block headerComment
#####################

#################
#block headTag /#
<HEAD>
<TITLE>$*title</TITLE>
$*metaTags
$*stylesheetTags
$*javascriptTags
</HEAD>
#end block headTag /#
#################


#################
#block bodyTag /#
$bodyTag
#end block bodyTag /#
#################

#block bodyContents /#
This skeleton page has no flesh. Its body needs to be implemented.
#end block bodyContents /#

</BODY>
</HTML>
"""

##################################################
## TEMPLATE SERVLET ##
        
class SkeletonPage(TemplateServlet):
    """A Skeleton HTML page template"""
    
    def __init__(self, template=template, *searchList, **kw):
        """ """
        self.loadMacrosFromModule(HTMLMacros)
        self.loadMacro('imgTag', self.imgTag )       
        TemplateServlet.__init__(self, template, *searchList, **kw)
       
    ## Default values for the names embedded in the template ##
    
    docType = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" ' + \
              '"http://www.w3.org/TR/html4/loose.dtd">'

    title = ''
    #_metaTags = {'HTTP_EQUIV':{'test':1234}, 'NAME':{'test':1234,'test2':1234} }
    #_stylesheets = {'.cssClassName':'stylesheetCode'}
    #_stylesheetLibs = {'libName':'libSrcPath'}
    #_javascriptLibs = {'libName':'libSrcPath'}
    bodyTagAttribs = {}
   
    siteDomainName = 'www.example.com'
    siteCredits = 'Designed & Implemented by Tavis Rudd'
    siteCopyrightName = "Tavis Rudd"
   

    def metaTags(self):
        """ """
        if not hasattr(self,'_metaTags'):
            return ''
        else:
            formatMetaTags(self._metaTags)
    
    def stylesheetTags(self):
        stylesheetTagsTxt = ''
        if hasattr(self,'_stylesheetLibs'):
            for title, src in self._stylesheetLibs.items():
                stylesheetTagsTxt += '<LINK REL="stylesheet" TYPE="text/css" HREF="' + str(src) + '">\n'
                
        if hasattr(self,'_stylesheets') and hasattr(self,'_stylesheetsOrder'):
            stylesheetTagsTxt += '<STYLE TYPE="text/css"><!--\n'
            for identifier in self._stylesheetsOrder:
                if not self._stylesheets.has_key(identifier):
                    warning = '# the identifier ' + identifier + \
                              'was in self._stylesheetsOrder, but not in self._stylesheets'
                    print warning
                    stylesheetTagsTxt += warning
                    continue
                    
                attribsDict = self._stylesheets[identifier]
                cssCode = ''
                attribCode = ''
                for k, v in attribsDict.items():
                    attribCode += str(k) + ': ' + str(v) + '; '
                attribCode = attribCode[:-2] # get rid of the last semicolon
                
                cssCode = '\n' + identifier + ' {' +  attribCode + '}'
                stylesheetTagsTxt += cssCode
            stylesheetTagsTxt += '\n//--></STYLE>\n'

        return stylesheetTagsTxt.strip()

    def javascriptTags(self):
        if not hasattr(self,'_javascriptTags'):
            return ''
        #else...
        javascriptTagsTxt = []
        if self._javascriptTags.has_key('libs'):
            for title, details in self._javascriptTags['libs'].items():
                if type(details) not in (types.ListType, types.TupleType):
                    details = ['',details]

                javascriptTagsTxt += ['<SCRIPT LANGUAGE="JavaScript', str(details[0]),
                                      '" SRC="', str(details[1]), '">\n']
        return ''.join(javascriptTagsTxt)
    
    def bodyTag(self):
        if not hasattr(self,'bodyTagAttribs'):
            self.bodyTagAttribs = {}

        bodyTagTxt = formHTMLTag('BODY', self.bodyTagAttribs)
        return bodyTagTxt


    def imgTag(self, src, alt='', width=None, height=None, border=0):
        """dynamically generate an image tag

        The dimensions are calculated using PIL or ImageMagick if they are available."""
        try:
            src = self.serverSidePath(src)
            print src
        except:
            pass
        
        try:
            if not width or not height:
                try:                    # see if the dimensions can be calc'd with PIL
                    import Image
                    im = Image.open(src)
                    calcWidth, calcHeight = im.size
                    del im
                except:
                    try:                # try imageMagick instead
                        calcWidth, calcHeight = os.popen('identify -format "%w,%h" ' + src).read().split(',')
                    except:
                        pass
                
            if not width: width = calcWidth
            if not height: height = calcHeight
            
            return ''.join(['<IMG SRC="', src, '" WIDTH=', str(width), ' HEIGHT=', str(height),
                           ' ALT="', alt, '" BORDER=', str(border), '>'])
        except:
            return ''.join(['<IMG SRC="', src, '" ALT="', alt, '" BORDER=', str(border),'>'])


##################################################
## if run from the command line ##
    
if __name__ == '__main__':
    SkeletonPage().runAsMainProgram()

