#! /usr/bin/env bash

[[ "$TOXENV" == *-flake8 || "$TOXENV" == pypy* ]] && exit 0

umask 022 &&
chmod -R a+rX . &&

pip install -U pip setuptools wheel twine &&
python setup.py sdist &&

if [ -d build ]; then find build -name '*.py[co]' -delete; fi &&
python setup.py build_ext &&
python setup.py build --executable '/usr/bin/env python' &&
python    -m compileall build &&
python -O -m compileall build &&
python setup.py bdist_wheel &&

py=`python -c "import sys; print('.'.join(sys.version.split('.')[:2]))"`
v="`echo $py | sed 's/\.//'`" &&

if [ $py = 2.7 ]; then
   pyenv global system 3.6.7 2.7.15
   pip3.6 install -U auditwheel
else
   pip install -U auditwheel
fi &&

cd dist &&
for f in Cheetah3-*-cp$v-*-linux_x86_64.whl; do
   if [ $py = 2.7 ]; then
      python3.6 -m auditwheel repair -w . $f
   else
      python -m auditwheel repair -w . $f
   fi &&
   rm $f
done &&
cd .. &&

exec twine upload --skip-existing dist/*
