#! /bin/sh

cd "`dirname \"$0\"`"/cheetah3 &&
../build-docs &&
rsync -ahP --del --exclude=.git --exclude=.nojekyll \
   www/html/ ../cheetahtemplate3.github.io/ &&

cd ../cheetahtemplate3.github.io &&
exec git status
