#! /bin/sh

tag="`python setup.py --version`" &&

. `dirname $0`/split_tag.sh &&
split_tag $tag

if [ $micro -eq 0 -a \( $state = final -o $state = post \) ] &&
      git branch --merged master | grep -Fqw maint; then
   git checkout maint &&
   git merge --ff-only master &&
   git checkout master
else:
   git checkout master &&
   git merge --ff-only maint ||
   git merge --strategy=ours -m 'Null-merge branch "maint"' maint
fi &&

git checkout $tag~ ANNOUNCE.rst &&

`git var GIT_EDITOR` ANNOUNCE.rst LATEST-CHANGES.rst docs/news.rst Cheetah/Version.py README.rst setup.cfg SetupConfig.py &&
exec git commit --message="Build: Prepare for the next release" --message="[skip ci]" ANNOUNCE.rst LATEST-CHANGES.rst docs/news.rst Cheetah/Version.py README.rst setup.cfg SetupConfig.py
