#! /bin/sh

if [ -z "$1" -o -n "$2" ]; then
   echo "Usage: $0 new_tag" >&2
   exit 1
else
   tag="$1"
fi

. `dirname $0`/split_tag.sh &&
split_tag $tag

if [ $micro -eq 0 -o $state != final -o $state != post ]; then
   git checkout master
else
   git checkout maint
fi &&

if [ $state = final -o $state = post ]; then
    ghr_prerelease=false
else
    ghr_prerelease=true
fi &&
sed -Ei "s/(^ +prerelease): .*\$/\1: $ghr_prerelease/" .github/workflows/test-publish.yaml &&

`git var GIT_EDITOR` ANNOUNCE.rst LATEST-CHANGES.rst docs/news.rst Cheetah/Version.py README.rst setup.cfg SetupConfig.py &&
exec git commit --message="Release $tag" ANNOUNCE.rst LATEST-CHANGES.rst docs/news.rst Cheetah/Version.py README.rst setup.cfg SetupConfig.py .github/workflows/test-publish.yaml
