#! /bin/sh

cd "`dirname \"$0\"`"/cheetah3 &&
umask 022 &&
chmod -R a+rX . &&

../build-docs &&
../set-commit-date.py &&

python setup.py build_ext &&
python setup.py build &&
python setup.py sdist &&
twine register dist/CT3-"`python setup.py --version`".tar.gz &&

for py in 2.7 3.4 3.5 3.6; do
   find build -name '*.py[co]' -delete &&
   python$py setup.py build_ext &&
   python$py setup.py build &&
   python$py    -m compileall build &&
   python$py -O -m compileall build &&
   python$py setup.py bdist_egg &&
   python$py setup.py bdist_wheel &&
   if [ "`echo $py | cut -c1`" -eq 3 ]; then
      cd dist &&
      for f in CT3-*-linux_i686.whl; do
         python$py -m auditwheel repair -w . $f &&
         rm $f
      done &&
      cd ..
   fi || exit 1
done

twine upload --sign dist/* &&
exec rm -rf build dist docs/html SQLObject.egg-info
