#! /bin/sh

cd "`dirname \"$0\"`"/.. &&
umask 022 &&
chmod -R a+rX . &&

set-commit-date.py &&
devscripts/build-docs &&

if [ ! -d build ]; then mkdir build; fi &&
python setup.py sdist &&

for py in 2.7 3.4 3.5 3.6 3.7 3.8; do
   find build -name '*.py[co]' -delete &&
   python$py setup.py build_ext &&
   python$py setup.py build --executable '/usr/bin/env python' &&
   python$py    -m compileall build &&
   python$py -O -m compileall build &&
   python$py setup.py bdist_wheel &&
   cd dist &&
   v="`echo $py | sed 's/\.//'`" &&
   for f in Cheetah3-*-cp$v-*-linux_*.whl; do
      if [ $py = 2.7 ]; then
         python3.6 -m auditwheel repair -w . $f
      else
         python$py -m auditwheel repair -w . $f
      fi &&
      rm $f
   done &&
   cd ..
done &&

twine upload --skip-existing dist/* &&
exec rm -rf build dist docs/html Cheetah3.egg-info
