#! /bin/sh

umask 022  # -rwxr-xr-x
cd "`dirname \"$0\"`"/cheetah3 &&

for py_ver in 2.7 3.3 3.4 3.5 3.6; do
   python$py_ver -m pip install --install-option=-O2 --upgrade .
done &&

exec rm -rf build dist Cheetah3.egg-info MANIFEST *.egg
